export const all_members = [
    {
        name : "Jaida Day",
        position : "Web Developer",
        year : "2022",
        github : "", 
        instagram: "", 
        linkedin: "",
        bio : "She a cutie :)", 
    },
    {
        name : "Jaida Day",
        position : "Web Developer",
        year : "2022",
        github : "", 
        instagram: "", 
        linkedin: "",
        bio : "She a cutie :)", 
    },
    {
        name : "Jaida Day",
        position : "Web Developer",
        year : "2022",
        github : "", 
        instagram: "", 
        linkedin: "",
        bio : "She a cutie :)", 
    },
    {
        name : "Jaida Day",
        position : "Web Developer",
        year : "2022",
        github : "", 
        instagram: "", 
        linkedin: "",
        bio : "She a cutie :)", 
    },
    {
        name : "Jaida Day",
        position : "Web Developer",
        year : "2022",
        github : "", 
        instagram: "", 
        linkedin: "",
        bio : "She a cutie :)", 
    },
    {
        name : "Jaida Day",
        position : "Web Developer",
        year : "2022",
        github : "", 
        instagram: "", 
        linkedin: "",
        bio : "She a cutie :)", 
    }
]