export const all_members = [
  {
    //picture: require("./demoPic.jpg")
    picture: require("../static/board-members/sydney.jpg"),
    name: "Sydney Wong",
    position: "President",
    year: "Class of 2023",
    email: "mailto:sywong@ucsd.edu",
    linkedin: "https://www.linkedin.com/in/sydney-wong-269a83193",
    instagram: "https://www.instagram.com/sydneywong8/",
    github: "",
    bio: "Hi everyone! I’m Sydney - a fourth year computer science major and business minor from Sixth college. I’m super excited to be this year’s co-president! A highlight from my summer was interning in New York and trying lots of different foods there."
  },
  {
    picture: require("../static/board-members/navika.jpeg"),
    name: "Navika Budhraja",
    position: "President",
    year: "Class of 2023",
    email: "mailto:nbudhraj@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hi, my name is Navika Budhraja! I’m a fourth year CS major in ERC. My summer highlights were visiting friends in LA and NYC, hanging out with my 9-month old niece (I swear I’m the cool aunt), and commuting to SF for my summer internship!"
  },
  {
    picture: require("../static/board-members/sarayu.jpeg"),
    name: "Sarayu Pai",
    position: "Vice President External",
    year: "Class of 2023",
    email: "mailto:s2pai@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hi everyone, I'm Sarayu Pai, a fourth year Bioinformatics and Computer Engineering double major in ERC, and I'm super excited to continue serving as one of WIC's Co-VP Externals! A highlight from my summer was spending time exploring Seattle and this year I'm looking forward to growing the WIC community and meeting new people :)"
  },
  {
    picture: require("../static/board-members/linda.jpg"),
    name: "Linda Long",
    position: "Vice President External",
    year: "Class of 2024",
    email: "mailto:llong@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hey everyone! My name is Linda Long. I major in Applied Mathematics and I have a junior standing in ERC. This year, I am looking forward the most about growing our WIC community and meeting all of you during our WIC events!"
  },
  {
    picture: require("../static/board-members/Lindsey.jpg"),
    name: "Lindsey Manzano",
    position: "Vice President Internal",
    year: "Class of 2024",
    email: "mailto:lmanzano@ucsd.edu",
    linkedin: "https://www.linkedin.com/in/lindsey-manzano-886a7316",
    instagram: "https://www.instagram.com/lindseymanzano/",
    github: "https://github.com/lindseymanzano",
    bio: "Hi! I'm Lindsey and I'm a rising third-year majoring in computer science in Marshall! This fall, I'm excited to dance with my hip hop team, reconnect with friends I haven't seen this summer, and serve as WIC’s VP Internal! I look forward to meeting you all at our WIC events and growing this organization’s wonderful community:)"
  },
  {
    picture: require("../static/board-members/jezebel.jpg"),
    name: "Jezebel Yangari",
    position: "Vice President Finance",
    year: "Class of 2025",
    email: "mailto:jyangari@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hello! I’m Jezebel, the new VP of Finance. My major is computer science. I’m a rising second year in Muir College. This year I am excited to meet some of the new students on campus and go to more events."
  },
  {
    picture: require("../static/board-members/haitong.jpg"),
    name: "Haitong Chen",
    position: "Secretary",
    year: "Class of 2023",
    email: "mailto:hac020@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Yo this is Haitong. I am a senior student majoring in Computer Science and from Revelle college. In my free time, I enjoy watching cooking videos and standup comedy shows. This summer I was interning in Dallas, and it was the first time I have been to Texas. I also paid a visit to Austin with no internet (data outage for my carrier) and my wallet lost… it was very fun, feeling like traveling back in 10 years ago!"
  },
  {
    picture: require("../static/board-members/Aiko.jpg"),
    name: "Aiko Coanaya",
    position: "Web Development Chair",
    year: "Class of 2024",
    email: "mailto:acoanaya@ucsd.edu",
    linkedin: "https://www.linkedin.com/in/aikocoanaya/",
    instagram: "",
    github: "https://github.com/aikocny",
    bio: "Hi everyone! I’m Aiko, WIC’s Web Development Chair this year. I am a junior studying Computer Science in Warren College. A highlight of my summer was interning in San Diego and exploring the city a bit more. In my spare time, I love to go on spontaneous trips, watch movies, and try new foods around the area. I am looking forward to meeting everyone this school year!"
  },
  {
    picture: require("../static/board-members/Kaitlin.jpg"),
    name: "Kaitlin Jarboe",
    position: "Technical Development Co-Chair",
    year: "Class of 2024",
    email: "mailto:kjarboe@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hi, I’m Kaitlin and I am a junior in Revelle college majoring in Computer Science and minoring in Music. In my free time I like to spend time with my cats, create 3d models, and crochet. The thing I’m looking forward to most about returning this Fall quarter is getting back into ballroom dancing :)"
  },
  {
    picture: require("../static/board-members/judy.jpg"),
    name: "Judy Liu",
    position: "Technical Development Co-Chair",
    year: "Class of 2023",
    email: "mailto:lel006@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hi! My name is Judy Liu, I am a senior computer science student from Warren college. During the summer I have lived and explored SF and the bay area. Some highlights include going to Great America, the Weeknd concert, and six flags! I love to try new things and explore new areas, and I look forward to meeting new people this Fall quarter!"
  },
  {
    picture: require("../static/board-members/Lily.jpg"),
    name: "Lily Steiner",
    position: "Social Co-Chair",
    year: "Class of 2023",
    email: "mailto:lsteiner@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hi, I’m Lily! I’m a 4th year student in Warren majoring in Computer Science with a specialization In bioinformatics. The highlight of my summer has been spending lots of time with my friends & also visiting NYC! I’m really looking forward to seeing you all at our socials again this year :)"
  },
  {
    picture: require("../static/board-members/nitya.jpg"),
    name: "Nitya Agarwal",
    position: "Social Co-Chair",
    year: "Class of 2024",
    email: "mailto:n3agarwa@ucsd.edu",
    linkedin: "https://www.linkedin.com/in/nitya-agarwal1/",
    instagram: "",
    github: "",
    bio: "Hello, I’m Nitya— 3rd year Computer Engineering major at Warren! I love meeting new people and look for new avenues towards self-improvement. I do like to stay in and just watch shows for a couple of hours with a bag of hot cheeto puffs too. A highlight from my summer is hiking at national parks, specifically Yosemite!"
  },
  {
    picture: require("../static/board-members/GingerS.jpg"),
    name: "Ginger Smith",
    position: "PR Marketing",
    year: "Class of 2025",
    email: "mailto:g4smith@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hi I’m Ginger! I’m a second year from Seattle studying CS and French and I’m in ERC! I’m excited about working on the PR team this year :) A highlight from my summer was paddleboarding at night and stargazing on the lake with one of my friends!"
  },
  {
    picture: require("../static/board-members/VivianW.jpg"),
    name: "Vivian Wu",
    position: "PR Marketing",
    year: "Class of 2023",
    email: "mailto:vrwu@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hi, I’m Vivian! I’m a fourth year CS^2 (comp sci / cog sci) major/minor and I’m in Warren College. Something fun that I did this summer was staying in and exploring Seattle. I was able to meet lots of cool people, eat lots of good food, and visit lots of cool places! I’m looking forward to meeting more cool people and doing cool things in the Fall quarter :)"
  },
  {
    picture: require("../static/board-members/VivianD.jpg"),
    name: "Vivian Dang",
    position: "PR Publicity",
    year: "Class of 2023",
    email: "mailto:vtdang@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hi everyone! I’m Vivian and I’m a fourth year math-cs major from Revelle college. A highlight from this summer was traveling to SF with my friends and exploring the bay area."
  },
  {
    picture: require("../static/board-members/Shreya.jpeg"),
    name: "Shreya Velagala",
    position: "First Year Chair",
    year: "Class of 2025",
    email: "mailto:svelagala@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hi, My name is Shreya, I am going to be a sophomore at UCSD this year majoring in Computer Science at Warren College. This summer I went to Canada for the first time and did some touristy things which was very exciting. Some fall quarter activities that I am looking forward to this year are the warren first week events."
  },
  {
    picture: require("../static/board-members/kelly.jpg"),
    name: "Kelly Park",
    position: "BPC Co-Chair",
    year: "Class of 2024",
    email: "mailto:khpark@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hello hello !! My name is Kelly, and I’m a 3rd year in Warren majoring in Data Science and minoring in Korean Studies! I’m super excited to be serving WIC as BPC Co-Chair this year! One thing I’m looking forward to for fall quarter is meeting new people through WIC and other orgs I’m involved in."
  },
  {
    picture: require("../static/board-members/melody.jpg"),
    name: "Melody Gill",
    position: "BPC Co-Chair",
    year: "Class of 2025",
    email: "mailto:mwgill@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hello! I'm Melody, and I am a second-year computer science major in Sixth College. A highlight from my summer was spending a weekend in San Francisco with my friends and getting to be tourists for a couple days. I'm excited to be BPC Co-Chair this year!"
  },
  {
    picture: require("../static/board-members/Helena.jpg"),
    name: "Helena Hundhausen",
    position: "Outreach Co-Chair",
    year: "Class of 2025",
    email: "mailto:hhundhausen@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hello I’m Helena, a second-year warren student majoring in computer science. This fall quarter I’m really looking forward to getting Blue Bowl on campus and meeting new people part of the WIC community! A highlight of my summer was visiting my best friends from high school and going to a Lumineers concert (even though our car got towed, lol)"
  },
  {
    picture: require("../static/board-members/lina.jpg"),
    name: "Lina Battikha",
    position: "Outreach Co-Chair",
    year: "Class of 2025",
    email: "mailto:lbattikha@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hi I’m Lina! I'm one of the co-outreach chairs for this upcoming school year! I'm a sophomore in Warren College, majoring in Data Science. One of my summer highlights is a mini trip I took to Palm Dessert with friends. Very excited to meet new people through WIC!! :)"
  },
  {
    picture: require("../static/board-members/advika.jpg"),
    name: "Advika Sonti",
    position: "Intern",
    year: "Class of 2025",
    email: "mailto:asonti@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Year: Second\nMajor: Cognitive Science\nCollege: Marshall\nWinter break highlight: Seeing my home friends!"
  },
  {
    picture: require("../static/board-members/danielle.jpg"),
    name: "Danielle Dang",
    position: "Intern",
    year: "Class of 2026",
    email: "mailto:d4dang@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Hi! I’m a first year student majoring in computer science from sixth college. A highlight of my winter break was being able to spend time with my family and eat lots of good food!"
  },
  {
    picture: require("../static/board-members/trinity.jpg"),
    name: "Trinity Oritz",
    position: "DEI Lead",
    year: "Class of 2025",
    email: "mailto:t3oritz@ucsd.edu",
    linkedin: "",
    instagram: "",
    github: "",
    bio: "Year: 2nd\nMajor: Business Economics\nCollege: Warren\nWinter break highlight: The highlight of my winter break was playing white elephant for the first time with my family for Christmas.\nLooking forward: I’m looking forward to spending more time on campus studying with my friends.\nFavorite WIC memory: My favorite WIC memory was last year during the paint and sip event where I painted Pepe the frog."
  },
  {
    picture: require("../static/board-members/wic.png"),
    name: "",
    position: "",
    year: "",
    email: "",
    linkedin: "",
    instagram: "",
    github: "",
    bio: ""
  },
];
